export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  MEMBER: "MEMBER",
};

export const ROUTE_PERMISSIONS = {
  "/dashboard": [ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  "/projects": [ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  "/team": [ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
  "/user": [ROLES.ADMIN],
  "/messages": [ROLES.ADMIN, ROLES.MANAGER, ROLES.MEMBER],
};
